services:
  - type: worker
    name: gigliotube-bot-ultra-potente
    env: python
    plan: free
    buildCommand: |
      apt-get update && 
      apt-get install -y ffmpeg && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: "Europe/Rome"
      - key: RENDER
        value: "true"
    autoDeploy: true
    branch: main
    repo: https://github.com/Presenze/super-youtube-music-bot
