services:
  - type: web
    name: gigliotube-bot
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python gigliotube.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/Presenze/super-youtube-music-bot
