services:
  - type: web
    name: gigliotube-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/Presenze/super-youtube-music-bot
